image: rbekker87/build-tools:latest

stages:
  - init

init:
  stage: init
  script:
    - apt-get update
    - apt-get install tesseract-ocr
    - apt-get install tesseract-ocr-eng
    - pip install -r requirements.txt
